# Site/SEO settings
email: matheusvieiracoelho@gmail.com
permalink: /:year/:month/:title/
google_analytics:

name: Matheus Seabra
title: Matheus Seabra | Software Engineer
description: Matheus Seabra is a Software Engineer based in Vitória, Brazil.
url: https://matheuseabra.me
twitter_username: matseabra

# Sass
sass:
  sass_dir: _assets/scss

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md

# Pagination
paginate: 3
paginate_path: "/page/:num/"

# Collections
collections:
  work:
    output: true
    permalink: /:path/
  skills:
    output: true
    permalink: /:path/
