# Site/SEO settings
email: matheusvieiracoelho@gmail.com
permalink: /blog/:title/
google_analytics: "UA-99071986-4"

name: Matheus Seabra
title: Matheus Seabra
description: FullStack JavaScript Development
url: https://matheuseabra.me
uri: https://matheuseabra.me
twitter_username: matseabra

# Sass
sass:
  sass_dir: _assets/scss

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor

# Pagination
paginate: 6
paginate_path: "/blog/page/:num/"

include:
 - _pages

# Collections
collections:
  work:
    output: true
    permalink: /:path/
  projects:
    output: true
    permalink: /:path/
  companies:
    output: true
    permalink: /:path/
  schools:
    output: true
    permalink: /:path/
  skills:
    output: true
    permalink: /:path/
