---
order: 3
title: "Testing, CI/CD & Deployment"
description: "Testing Driven Development (TDD) reduces the number of bugs released during deployment, making it critical to ship effective applications to production."
tags:
  - Pytest
  - Jest
  - Cypress
  - CircleCI
  - Docker
  - Amazon Web Services
  - Linux
  - Git
---

